#!/usr/bin/python

import cv2
import rospy

from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError


class CameraProcessor(object):

    def __init__(self):

        self.__imgSubscriber = rospy.Subscriber(
            'roskeycar/camera/image_color/BGR/raw',
            Image,
            queue_size=1,
            callback=self.onImageReceived)

        self.__bridge = CvBridge()


    def onImageReceived(self, msg):

        img = self.__bridge.imgmsg_to_cv2(msg)
        print('{0} : {1}'.format(msg.header.seq, img.shape))

        # TODO: do processing here


def main():

    rospy.init_node('camera_processing')

    processor = CameraProcessor()

    rospy.spin()


if __name__ == '__main__':
    main()
