#!/usr/bin/python

import rospy
from geometry_msgs.msg import Twist


def main():

    rospy.init_node('donkey_teleop')

    rate = rospy.Rate(0.25)  # 0.25 Hz

    publisher = rospy.Publisher('/donkey/twist',
                                Twist,
                                queue_size=1)

    multiplier = [-1.0, 0.0, 1.0]

    angle = -1.0
    linear = -1.0

    counter = 0

    while not rospy.is_shutdown():
        print(multiplier[counter])

        twist = Twist()
        twist.angular.z = angle * multiplier[counter]
        twist.linear.y = linear * multiplier[counter]
        publisher.publish(twist)

        counter = 0 if counter % 3 == 2 else counter + 1

        rate.sleep()


if __name__ == '__main__':
    main()
